### ISSUE TITLE
Greedy Regex on footnotes

### ISSUE THREAD

**Issue by scotartt** [scotthartley/PandocSyntax#1]
Line 264: 
- match: ([^)(.*)(])[^:]              # Footnote marker

should be:
- match: ([^)(.*?)(])[^:]              # Footnote marker

If you have multiple footnotes in a paragraph, the former will match both footnotes and all the text in-between. I would have submitted a pull request but I suspect that this issue will occur in more than the one place. It's the same for inline footnotes.

Test Text. This is the test text with a first footnote.[^1] There is also a second footnote.[^2] There is no footnote here.

[^1]: The first footnote.

[^2]: The second footnote.

**Comment by scotthartley** [comment]
Thanks!
