### ISSUE TITLE
Multi-citation in inline footnote

### ISSUE THREAD

**Issue by scotartt** [scotthartley/PandocSyntax#2]
In pandoc you can make a citation like this:

Some waffle I need to cite.^[@Levene2010 [p.72]; @Fabrizi2015 [p.119]; @Horsfall1985 [p.199]]

This results in a footnote with the citations formatted as follows (depending on your latex citation styles of course):

> Levene (2010 : 72); Fabrizi (2015 : 119); Horsfall (1985 : 199)

In pandoc the text looks like the following (with the edit I suggested in issue #1 manually applied).

<img width="963" alt="screenshot 2016-07-15 12 27 14" src="https://cloud.githubusercontent.com/assets/2726118/16861801/8b724dbe-4a87-11e6-83fb-5da30b89e81d.png">

**Comment by scotartt** [comment]
I've got a fix for this in the version that I forked: I'll try to put together a pull request.

**Comment by scotthartley** [comment]
Please do, that would be great. Coming from the chemistry side, this style of citations doesn't really come up so it was way off my radar.
