### ISSUE TITLE
Enhancement request: Highlight bullets

### ISSUE THREAD

**Issue by AndrewC-B** [scotthartley/PandocSyntax#3]
This is a really handy project. Thanks! One tiny suggestion/request: Could bullets (like - and *) be highlighted somehow? I often use these as points of reference in my document and I'd love it if they were coloured for quicker recognition. To clarify, I'm talking about the bullets themselves, not the text that goes with them.

Thanks again!

**Comment by scotthartley** [comment]
Thanks! Glad that your finding this helpful.

I don't think it would be too difficult to implement coloring the bullet markers, but I kind of reluctant to do it. The idea was to have this stick as closely as possible to the Pandoc structure and use logical scopes found in the Monokai Extended theme. I guess the biggest concession to this was that I set the various control characters to be colored as comments.

Lists should already be assigned the `markup.list.unnumbered.markdown` scope, should it should be very easy to modify the theme you're using to color the whole block. Does that help?

**Comment by AndrewC-B** [comment]
I'll give it a shot, thanks!

Another thing which would be handy is highlighting for inline Latex. 

I've managed to get this working in the past in a .tmLanguage file with syntax as shown below. Unfortunately I couldn't get this working with my own customisations to the Markdown syntax. Perhaps you might have more luck? If I get a chance I might try and get this working myself 😊

```
patterns = (
        {   include = 'text.tex.latex'; },
        {   include = 'text.html.markdown'; },
    );
```

**Comment by scotthartley** [comment]
Some basic LaTeX support is a great idea. It might take me a while to 
get to it, so please do push an update if you make progress.

Subject22 wrote:

**Comment by scotthartley** [comment]
Actually did play around with this a little. I can't figure out how to get it to implement proper LaTeX syntax highlighting (e.g., between \begin{} and \end{} commands), but I've added some very rudimentary support for LaTeX commands. Simple commands are treated like other control characters, \begin{} and \end{} like fenced code blocks. At least for my usage that seems to make the most sense.
