### ISSUE TITLE
Not available in Package Control

### ISSUE THREAD

**Issue by vbwx** [scotthartley/PandocSyntax#4]
Thanks for this syntax file, it works great!

Could you publish it on [packagecontrol.io](https://packagecontrol.io/docs/submitting_a_package)? This would make it easier for pandoc users to add this syntax.

**Comment by scotthartley** [comment]
Thanks! I'll look into it once the workload lightens up a bit. This sort of started out as an experiment for my own personal use and then I've just been adding to it as I run into issues, so it's a bit of a Frankenstein's monster right now. Once I find a little time to clean it up and make some more deliberate design decisions I'll try to make it more broadly available.
