### ISSUE TITLE
More inline citations

### ISSUE THREAD

**Issue by scotartt** [scotthartley/PandocSyntax#5]
These are also valid inline citation styles which don't fully work in the current version in master branch

    reprehenderit involuptate velit esse cillum 
    dolore eu fugiat nulla pariatur.^[inline with [@citation].]
    Excepteur sint occaecat cupidatat 
    non proident^[[@citation p.22; @citation; citation p.1].]

((I have installed a new Mac, so I'm piecing together my environment)).

This works on my old Mac; I will be using an old version and/or self-modified. I'll try to dig out the syntax which works on that.

scot

**Comment by scotthartley** [comment]
I think this should be fixed now. Let me know if it doesn't work!
