### ISSUE TITLE
problem with embedded brackets inside footnotes

### ISSUE THREAD

**Issue by palinurus** [scotthartley/PandocSyntax#6]
Unless part of an @-tagged reference, embedded brackets cause footnote highlighting to terminate "early." That is:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.^[I love Latin!] Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.^[I REALLY love Latin, as does @LatinLover2019 [34-36].] Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.^[I really (really [REALLY]) love Latin!]

will produce properly flagged text, reference, and footnotes--except for ") love Latin!]" which will be unmarked, as the syntax definition takes the footnote to end with the first right bracket. 

In the other pandoc syntax for Sublime Text (available via the "Pandoc Academic" package), the footnote highlighting is by contrast overly greedy: if a paragraph has multiple inline notes, both the notes and all the text in between is highlighted (or the same behavior as yours can be generated by changing `(.*)` to `(.*?)` in its syntax file). 

As problems go, this is very minor. But is there any way to adjust the syntax to handle nested brackets without being either overly greedy or overly parsimonious? 

Many thanks!

**Comment by scotthartley** [comment]
I think I've got this fixed. It will only handle one level of nested brackets. More could be added, although I'm guessing that doesn't come up much.
